### ISSUE TITLE
Fix duplicate avatars in People column of overview page

### ISSUE THREAD

**Issue by 2m** [drewhk/akka-minion#15]
There are some duplicate avatars displayed in the People column. I think it is because it counts them once for commenting on the PR and again while approving or requesting changes.

**Comment by drewhk** [comment]
I noticed the same. Thanks for filing it.

**Comment by 2m** [comment]
Relevant code is here: https://github.com/drewhk/akka-minion/blob/1fbe58ff9ecf02754bfcacc5d0f8fe570e2385cc/src/main/scala/akka/minion/Dashboard.scala#L151-L157
